autor = str(input('Escreva o nome do autor conforme o exemplo: SOBRENOME, Nome:'))
titulo = str(input('Escreva o título da obra:'))
subtitulo = str(input('Escreva o subtitulo da obra:'))
edicao = int(input('Escreva a edição da obra:'))
local_publicacao = str(input('Escreva o local de publicação:'))
editora = str(input('Escreva o nome da editora:'))
data =int(input('Escreva a data de publicação:'))
print('{}.{}:{}. {}ed. {}: {},{}.' .format(autor,titulo, subtitulo,edicao,local_publicacao, editora, data))
